CMSforSite-master/CMS.Web/Models/PhotoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using CMS.Domain;
using CMS.Domain.Interfaces;
using CMS.Domain.Models;
using PagedList;

namespace CMS.Web.Models
{
    public class PhotoViewModel
    {
        MappingEntities mapping = new MappingEntities();
        public PhotoViewModel(int year, int month, string title, IPhoto photoRepository, IPosts blogRepository)
        {
            LatestPosts = blogRepository.Post(year, month, title);
            if (LatestPosts != null)
            {
                var post = mapping.GetPostsById(LatestPosts.id);
                if (post.Album != null)
                    Photos = photoRepository.PhotosForAlbum(post.Album.id);
            }

           
        }
        public PhotoViewModel(Guid Id, IPhoto photoRepository, ICategories categoryRepository)
        {
            Categories = categoryRepository.Category(Id);
            if (Categories != null)
            {
                var post = mapping.GetCategoryById(Categories.id);
                if (post.Album != null)
                {
                    var album = photoRepository.PhotosForAlbum(post.Album.id);
                    if (album != null)
                    {
                        Photos = photoRepository.PhotosForAlbum(post.Album.id);
                    }
                }
                   

            }
        }


        public IList<Photos> Photos
        { get; private set; }
        public Categories Categories
        { get; private set; }


        public Posts LatestPosts
        { get; private set; }
    }
}

CMSforSite-master/CMS.Web/Controllers/BlogController.cs
using CMS.Domain.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using CMS.Domain.Models;
using CMS.Web.Models;

namespace CMS.Web.Controllers
{
    public class BlogController : Controller
    {
        // GET: Blog

        private readonly IPosts _blogRepository;
        private readonly IPhoto _photoRepository;
        private readonly ICategories _categoryRepository;
        public BlogController(IPosts blogRepository, IPhoto photoRepository, ICategories categoryRepository)
        {
            _blogRepository = blogRepository;
            _photoRepository = photoRepository;
            _categoryRepository = categoryRepository;
        }
        public ViewResult Posts(int ? page)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            var posts = _blogRepository.PostsList();
            if (posts.Count > 0)
            {
                return View(posts.ToPagedList(pageNumber, pageSize));
            }
            else
            {
                return View();
            }

        }
        public ViewResult Post(int year, int month, string title)
        {
            var post = _blogRepository.Post(year, month, title);

            if (post == null)
                throw new HttpException(404, "Post not found");

            if (post.Published == false && User.Identity.IsAuthenticated == false)
                throw new HttpException(401, "The post is not published");

            return View(post);
        }
        public ViewResult Art(Guid id)
        {
            var post = _blogRepository.Post(id);

            if (post == null)
                throw new HttpException(404, "Post not found");

            if (post.Published == false && User.Identity.IsAuthenticated == false)
                throw new HttpException(401, "The post is not published");

            return View("Post", post);
        }
        public ViewResult Category(string category)
        {
           
            //int pageSize = 10;
            //int pageNumber = (page ?? 1);
            var catt = _blogRepository.CategoriesList().FirstOrDefault(t => t.UrlSlug == category);
          //  var cat = _blogRepository.PostsForCategory(category);
           if(catt != null)
            {
                return View("Article", catt);
            }
           else
            {
                return View("Posts");
            }
        }
        [ChildActionOnly]
        public PartialViewResult Sidebars()
        {
            var widgetViewModel = new WidgetViewModel(_blogRepository);
            return PartialView("_Sidebars", widgetViewModel);
        }
        [ChildActionOnly]
        public PartialViewResult PhotoBar(int year, int month, string title)
        {
            var widgetViewModel = new PhotoViewModel(year, month, title, _photoRepository, _blogRepository);
            return PartialView("PhotoBar", widgetViewModel);
        }
        //[ChildActionOnly]
        //public PartialViewResult Sidebar()
        //{
        //    var widgetViewModel = new WidgetViewModel(_categoryRepository);
        //    return PartialView("_Sidebars", widgetViewModel);
        //}
        [ChildActionOnly]
        public PartialViewResult PhotoBars(Guid id)
        {
            var widgetViewModel = new PhotoViewModel(id, _photoRepository, _categoryRepository);
            return PartialView("PhotoBars", widgetViewModel);
        }

    }
}

CMSforSite-master/CMS.Web/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CMS.Domain.Interfaces;
using CMS.Web.Models;
using PagedList;

namespace CMS.Web.Controllers
{
    public class CategoryController : Controller
    {
        // GET: Category

        private readonly IPhoto _photoRepository;
        private readonly ICategories categoriesRepository;
        public CategoryController(ICategories _categoriesRepository, IPhoto photoRepository)
        {
            categoriesRepository = _categoriesRepository;
            _photoRepository = photoRepository;
        }
     
        public ActionResult Categories(int? page)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            var categories = categoriesRepository.Categories();
            if (categories.Count > 0)
            {
                return View(categories.ToPagedList(pageNumber, pageSize));
            }
            else
            {
                return View();
            }
        }
        public ViewResult Category(int? page)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            var categories = categoriesRepository.Categories();
            if (categories.Count > 0)
            {
                return View(categories);
            }
            else
            {
                return View();
            }
        }
        public ViewResult Article(Guid id)
        {
            var post = categoriesRepository.Category(id);

            if (post == null)
                throw new HttpException(404, "Post not found");

           

            return View(post);
        }
        [ChildActionOnly]
        public PartialViewResult Sidebars()
        {
            var widgetViewModel = new WidgetViewModel(categoriesRepository);
            return PartialView("_Sidebars", widgetViewModel);
        }
        [ChildActionOnly]
        public PartialViewResult PhotoBar(Guid id)
        {
            var widgetViewModel = new PhotoViewModel(id, _photoRepository, categoriesRepository);
            return PartialView("PhotoBar", widgetViewModel);
        }
    }
}

CMSforSite-master/CMS.Web/Controllers/FeedbackController.cs
using CMS.Domain.Interfaces;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CMS.Domain.Models;
using Newtonsoft.Json;

namespace CMS.Web.Controllers
{
    public class FeedbackController : Controller
    {
        // GET: Feedback
        private readonly IFeedback _feedbackRepository;
        public FeedbackController(IFeedback feedbackRepository)
        {
            _feedbackRepository = feedbackRepository;
        }
        public ActionResult FeedBacks(int? page)
        {
            var news = _feedbackRepository.AllFeedbacks();
            if (news.Count > 0)
            {
                return View(news);
            }
            else
            {
                return View();
            }
        }
       [ValidateInput(false)]
       [HttpPost]
        public ActionResult AddFeedback(Feedback feedback)
        {
            if (TryValidateModel(feedback))
            {
               _feedbackRepository.CreateArticle(feedback);
                return View();
            }
            else
            {
                return View("Error");
            }
        }

    }
}

CMSforSite-master/CMS.Web/Controllers/UslugiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CMS.Domain.Interface;

namespace CMS.Web.Controllers
{
    public class UslugiController : Controller
    {
        // GET: Uslugis
        private readonly IUsligi _usligiRepository;
        public UslugiController(IUsligi usligiRepository)
        {
            _usligiRepository = usligiRepository;
        }
        public ViewResult Services(int? page)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            var uslugi = _usligiRepository.ListOfService();
            if (uslugi.Count > 0)
            {
                return View(uslugi);
            }
            else
            {
                return View();
            }

        }
        public ViewResult Service(Guid id)
        {
            var service = _usligiRepository.Service(id);

            if (service == null)
                throw new HttpException(404, "Post not found");

           
            return View(service);
        }
    }
}

CMSforSite-master/CMS.Web/Views/Category/Article.cshtml
@model CMS.Domain.Categories

@{
    ViewBag.Title = Model.Name;
    ViewBag.Meta = Model.Meta;

    Layout = "~/Views/Blog/_layoutblog.cshtml";
}

<div id="content">
    <div class="post">
        <div class="post-meta">  
            <div class="row">
                <div class="post-title">
                    <h1>@Html.Raw(Model.Name)</h1>
                    @Html.Action("PhotoBar")
                </div>

            </div>
            <div class="row">
                <div class="post-category">
                    @*<span>Category:</span>&nbsp;@Html.CategoryLink(Model.Category)*@
                </div>
            </div>
        </div>
        <div class="post-body">
            @Html.Raw(Model.Description)
        </div>


    </div>

</div>

CMSforSite-master/CMS.Web/Views/Category/Category.cshtml
@model IList<CMS.Domain.Categories>
@{
    ViewBag.Title = "Интересные места Вьетнама";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Интересные места Вьетнама</h2>

<div class="sidebar">
    @if (Model != null)
    {
    <ul>
        @foreach (var post in Model)
    {


        <li>@Html.Raw(post.Name)</li>

        <li class="post-foot">@Html.ActionLink("Краткое описание....", "Article", new { id=post.id})</li>
     }
    </ul>
    }
    else
    {
        <p>Нет статей!</p>
    }
</div>

CMSforSite-master/CMS.Web/Views/Category/PhotoBar.cshtml
@model CMS.Web.Models.PhotoViewModel

<div id="sidebars">
    @if (Model.Photos != null)
    {
        @Html.Partial("_Photos", Model.Photos)
    }

</div>

CMSforSite-master/CMS.Web/Views/Category/_Categories.cshtml
@model IList<CMS.Domain.Categories> 

<!-- Widget to display categories in sidebar -->
<div class="sidebar">
    <h3>Места</h3>

    @if (Model.Count > 0)
    {
        <ul>
            @foreach (var category in Model)
            {
                <li>@Html.CategoryLink(category)</li>
            }
        </ul>
    }
    else
    {
        <p>Не заведено ни одного места во Вьетнаме!</p>
    }
</div>

CMSforSite-master/CMS.Web/Views/Category/_Photos.cshtml
@model IList<CMS.Domain.Models.Photos>
<style type="text/css">
    .slideshow {
        width: 580px;
        height: 400px;
        margin: auto;
    }

    .slideshow img {
        padding: 15px;
        border: 1px solid #ccc;
        background-color: #eee;
           
           
    }
</style>
<!-- include Cycle plugin -->
<script src="@Url.Content("~/Scripts/jquery.cycle.all.js")" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('.slideshow').cycle({
            fx: 'fade',
            speed: 'slow',
            timeout: 5000,
            next: '.slideshow',
            prev: '#prev'
        });

    });
</script>
<div class="slideshow">
    @if (Model != null)
    {
        foreach (var image in Model)
        {
            <div id="over" style="position: absolute; width: 100%; height: 100%;float:left ">
                @Html.Raw("<img  style='width:580px; height:380px;' src=\"data:image/jpeg;base64,"
                          + Convert.ToBase64String(image.Photo) + "\" />")
            </div>
        }
    }
</div>

CMSforSite-master/CMS.Web/Views/Category/_Sidebars.cshtml
@model CMS.Web.Models.WidgetViewModel

<div id="sidebars" >
    @Html.Partial("_Categories", Model.Categories)
  
</div>

CMSforSite-master/CMS.Web/Views/Category/_layoutblog.cshtml
@using System.Configuration

@{
    Layout = null;
    //var action = ((string)ViewContext.RouteData.Values["Action"]).ToLower();

    //var blogTitle = ConfigurationManager.AppSettings["BlogTitle"];
    //var feedBurnerUrl = ConfigurationManager.AppSettings["FeedBurnerUrl"];
}

<!DOCTYPE html>

<html>

<head>

    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">

    <title>Русскоязычный гид во Вьетнаме; Помощь в оформлении визы; Проведение экскурсий; Организация проживания в Хошимине.</title>
    @*@Styles.Render("~/Content/themes/simple/admin.css")*@
    @Styles.Render("~/Content/themes/simple/style.css")
    @Scripts.Render("~/jquery", "~/jqueryval", "~/jqueryunobtrusiveval", "~/js")
    @Scripts.Render("~/Scripts/jquery-1.8.2.js")
    @Scripts.Render("~/Scripts/jquery-ui.min.js")
    @Scripts.Render("~/Scripts/jquery-ui.js")
    @Scripts.Render("~/Scripts/admin.js")
</head>
<body>

    <div id="main">

        <!-- Header & Navigation -->
        <div id="header">
            <a href="@Url.Action("Index", "Home")">
                <img style="padding: 0 0 0 200px;" src="~/Content/Logotip.png" alt="" />
            </a>
            <div id="menubar" class="logo_colour">

                <ul id="menu">
                    <li class="logo_colour">@Html.ActionLink("Обо мне", "Index", "Home")</li>
                    <li class="logo_colour">@Html.ActionLink("Услуги", "Services", "Uslugi")</li>
                    <li class="logo_colour">@Html.ActionLink("О Вьетнаме", "Posts", "Blog")</li>
                    <li class="logo_colour">@Html.ActionLink("Достопримечательности", "Category", "Category")</li>
                    <li class="logo_colour">@Html.ActionLink("Отзывы туристов", "FeedBacks", "Feedback")</li>
                    <li class="logo_colour">@Html.ActionLink("Контакты", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
        <!-- Main Content -->
        <div id="site_content">
            @Html.Partial("_Search")
            @RenderBody()
            @Html.Action("Sidebars")
        </div>

        <!-- Footer -->
        <div id="footer">

            <!-- HotLog -->
            <span id="hotlog_counter"></span>
            <span id="hotlog_dyn"></span>
            <script type="text/javascript">
				var hot_s = document.createElement('script'); hot_s.type = 'text/javascript'; hot_s.async = true;
				hot_s.src = 'http://js.hotlog.ru/dcounter/2574588.js';
				hot_d = document.getElementById('hotlog_dyn');
				hot_d.appendChild(hot_s);
            </script>

            <noscript>
                <a href="http://click.hotlog.ru/?2574588" target="_blank">
                    <img src="http://hit20.hotlog.ru/cgi-bin/hotlog/count?s=2574588&im=407"
                         border="0" alt="HotLog" title="HotLog">
                </a>
            </noscript>
            <!-- /HotLog -->
            Copyright © @DateTime.Now.Year IT-Sugars All Rights Reserved
        </div>
    </div>
</body>
</html>